name: chess_pgn_reviser
description: Load your chess PGN file and try to find moves (from your side).

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  chess: ^0.6.6
  chess_vectors_flutter: ^1.0.12
  toast: ^0.1.5
  petitparser: ^4.1.0
  file_selector: ^0.7.0
  file_selector_linux: ^0.0.2
  file_selector_web: ^0.7.0
  confirm_dialog: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: FreeSerif
      fonts:
        - asset: fonts/FreeSerif.ttf